# Generated by Django 3.0.6 on 2020-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('doc_link', models.FileField(upload_to='')),
                ('page', models.CharField(choices=[('background', 'Background'), ('alice_deal', 'Alice Deal'), ('school', 'School')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('transcript', models.CharField(blank=True, max_length=10000, null=True)),
                ('comment', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
