# Generated by Django 3.0.6 on 2020-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='transcript',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
