# Generated by Django 3.0.6 on 2020-10-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201025_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_pic',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='thumbnail_images/'),
        ),
    ]
