# Generated by Django 3.0.6 on 2020-10-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_doc_is_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_is_pdf',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
