# Generated by Django 3.0.6 on 2020-10-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201027_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_is_pdf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
